# fly.toml app configuration file generated for lmgyms on 2023-08-23T22:46:13+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "lmgyms"
primary_region = "ams"

[build]

[http_service]
  internal_port = 5454
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
